### ISSUE TITLE
error in atacpipe2

### ISSUE THREAD

**Issue by Xcubitor** [wzthu/esATAC#124]
Hello guys, When I execute atacpipe2 command I always get the following error regardless of the input samples. It happens during the processing of the control case.

start processing(paired end data): PeakCallingFseq
Error in .jcall("edu/duke/igsp/gkde/Main", "V", "main", argvs) : 
  java.lang.ArithmeticException: / by zero

Does anybody have an idea or a solution to this? Thanks :-)

**Comment by wzthu** [comment]
Please try to re-install rJava and esATAC.

**Comment by AquariusCG** [comment]
I met the same error. I used the atacRepsPipe2() to perform intergroup comparison for multi-samples. Other samples were well done except of one that showed this error, so that the execution halted. I was sure that the rJava and esATAC were installed successfully, and library(rJava) was OK.  
How to solve this problem?

**Comment by Wan-Yifei** [comment]
I called atacPipe() for 4 samples separately. One of the samples occurs above error. But the others generated reports correctly. It's weird. 
```
2019-06-17 17:00:49
start processing(paired end data): PeakCallingFseq
Error in .jcall("edu/duke/igsp/gkde/Main", "V", "main", argvs) :
  java.lang.ArithmeticException: / by zero
Calls: atacPipe ... processing -> .fseq_call -> fseq -> .jcall -> .jcheck
```
