### ISSUE TITLE
sam to bam conversion output differs from bam file from samtools 

### ISSUE THREAD

**Issue by ritma001** [wzthu/esATAC#125]
Hi,

I converted sam to bam file using `sam2bam` provided in esATAC package. I would like to add this step to my esATAC pipline. However, it gave me 488M BAM file which is quite different from 605M BAM file using `$samtools view -b -S file.sam file.bam`. I looked at the source code of `sam2bam` in GitHub and could not find the default arguments to compare with `samtools`. I would be glad if you could help me figure it out so, I feel more confident to include `sam2bed` in a pipeline.  Thank you in advance for your response.

**Comment by Honchkrow** [comment]
Hi,
I reproduced your problem. I think that this problem is caused by whether the bam file is sorted or not.
U can try the following command.
using esATAC:
`sam2bam(samInput = "test.sam")`

using linux command line:
`samtools view -b -S test.sam > samtools.nsorted.bam`  #not sorted
`samtools view -b -S test.sam | samtools sort - > samtools.sorted.bam`  # sorted

I see the output file size from esATAC is equal to the "samtools.sorted.bam", but "samtools.nsorted.bam"is larger.

You can try these command. If you find any question, please let me know and I am very happly to help you.

**Comment by Honchkrow** [comment]
Also, I checked the bed output from these two bed file, they are the same.

Wei

**Comment by ritma001** [comment]
Dear Wei,

Thank you for the explanation. I did check the sorted and unsorted bam files as well as the converted sam files. The result of esATAC is indeed the same as sorted bam provided from samtools. A million thank again.

Wannisa
