### ISSUE TITLE
Error in RMotifScan

### ISSUE THREAD

**Issue by xbjie123** [wzthu/esATAC#133]
Hi Zheng,

When I run esATAC to the RMotifScan step, I get an error like this,

`Error in loadFUN(x, seqname, ranges) : 
  trying to load regions beyond the boundaries of non-circular sequence "chrUn_KN150437v1"`

In fact, I get the similar error when I run one replicated samples via atacRepsPipe. 
Would you mind showing me the proper way to deal with this issue?

Thanks a lot
BJ

**Comment by wzthu** [comment]
@Honchkrow , can you please to have a look?

**Comment by Honchkrow** [comment]
@xbjie123 , sorry for late response.
 The function RMotifScan needs two main parameters, one is the peak file,  another is the motif pwm/pfm matrix. Your problem is related to the peak file. The function get sequences according to your peak file, but at a peak in chrUn_KN150437v1, the region is beyond the boundaries of chrUn_KN150437v. I recommend you check your peaks in chrUn_KN150437v1, especially the boundaries.    
You may use macs to see  whether this beyond boundary question exists or not. If not, please provide the sample session number, I will reproduce your problem and modify functions to fix it.

Zhang Wei
